name: Commit Tests

on:
  push:

jobs:
  build_experiment:
    name: Hit if
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - name: Hi from ${{ matrix.os }}
      if: startsWith(matrix.os, 'windows')
      run: echo Hello from Windows
    - name: Hi from ${{ matrix.os }}
      if: startsWith(matrix.os, 'windows') == false
      run: echo Hello from not Windows
